// ONTARIO ACTIONS
export const GET_ALL_CASES = 'GET_ALL_CASES';
export const GET_CASES_BY_REGION = 'GET_CASES_BY_REGION';
export const GET_REGION_DATA = 'GET_REGION_DATA';
export const GET_VACCINATIONS = 'GET_VACCINATIONS';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const CLEAR_SELECTED_DATE = 'CLEAR_SELECTED_DATE';