// ONTARIO ACTIONS
export const GET_ALL_CASES = 'GET_ALL_CASES';
export const GET_CASES_BY_REGION = 'GET_CASES_BY_REGION';
export const GET_VACCINATIONS = 'GET_VACCINATIONS';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const CLEAR_SELECTED_DATE = 'CLEAR_SELECTED_DATE';
export const SET_SAVED_REGIONS = 'SET_SAVED_REGIONS';
export const REMOVE_SAVED_REGION = 'REMOVE_SAVED_REGION';
export const ADD_SAVED_REGION = 'ADD_SAVED_REGION';

// COUNTRIES ACTIONS
export const GET_ALL_COUNTRIES_DATA = 'GET_ALL_COUNTRIES_DATA';
export const COUNTRIES_ERROR = 'COUNTRIES_ERROR';

// ALERT ACTIONS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';